USE codeup_test_db;
DROP TABLE IF EXISTS albums;
CREATE TABLE albums(
   id INT UNSIGNED NOT NULL AUTO_INCREMENT,
   artist VARCHAR(200) NOT NULL,
   name VARCHAR(200) NOT NULL,
   release_date INT UNSIGNED,
   sales FLOAT UNSIGNED,
   genre VARCHAR (100),
   PRIMARY KEY(id)
);
SHOW TABLES;
DESCRIBE albums;
SHOW CREATE TABLE albums;
SHOW TABLES;
