USE codeup_test_db;

-- Write SELECT statements to output each of the following with a caption:
--
    -- All albums in your table.
    -- Make all the albums 10 times more popular (sales * 10)
-- SELECT sales, name AS 'Table of Albums' FROM albums;
-- UPDATE albums
-- SET sales = (sales*10);
-- SELECT * FROM albums;
    -- All albums released before 1980
    -- Move all the albums before 1980 back to the 1800s.
-- SELECT name AS 'Albums Released Before 1980' FROM albums WHERE release_date < 1980;
-- UPDATE albums
-- SET release_date = 1800
-- WHERE release_date BETWEEN 1980 AND 1989;
-- SELECT name AS 'Moved to 1800''s' FROM albums WHERE release_date < 1900;
    -- All albums by Michael Jackson
    -- Change 'Michael Jackson' to 'Peter Jackson'
-- SELECT artist AS 'Albums by Michael Jackson' FROM albums WHERE artist = 'Michael Jackson';
-- UPDATE albums
-- SET artist = 'Peter Jackson'
-- WHERE artist = 'Michael Jackson';
-- SELECT artist AS 'Albums by Michael Jackson???' FROM albums WHERE artist = 'Peter Jackson';
